# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '88:80'
            - '${VITE_PORT:-5174}:${VITE_PORT:-5174}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-33061}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
            - pma_networks
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    pma:
        image: phpmyadmin:latest
        restart: always
        healthcheck:
            interval: 120ms
            retries: 5
            start_period: 60ms
            test: |
                touch /tmp/healthcheck.txt &&
                mkdir /tmp/healthcheck &&
                mv /tmp/healthcheck.txt /tmp/healthcheck &&
                cd /tmp/healthcheck &&
                echo "hello my docker container is working fine" >> healthcheck.txt &&
                cat healthcheck.txt &&
                rm healthcheck.txt &&
                cd .. &&
                rmdir /tmp/healthcheck
                cls
            timeout: 30ms
        environment:
        - PMA_ARBITRARY=1
        ports:
        - 3338:80
        depends_on:
        - mysql
        volumes:
        - pma-data:/var/lib/phpmyadmin/data
        networks:
        - pma_networks
networks:
    pma_networks:
    sail:
        driver: bridge
volumes:
    pma-data:
    sail-mysql:
        driver: local
